### ISSUE TITLE
Configure gamepad input freezes the CX II

### ISSUE THREAD

**Issue by critor** [ndless-nspire/Ndless#258] opened 2020-11-17 19:47 UTC
TI-Nspire CX II CAS 5.2.0.771 revision AE.

No need to load any ROM.

Go to "configure gamepad input".
Select the control you'd like to reassign a key for.
Press [enter].
The calculator prompts you to "press for a key" :
https://tiplanet.org/forum/images/forum_uploads/2043_1605639241_5fb41c49c2a43.png
But all key presses are then ignored, you have to reboot the calculator.

https://tiplanet.org/forum/viewtopic.php?f=15&t=24408

**Comment by RuralAnemone** [comment] 2020-11-18 17:58
I'm getting that on my CX II as well (not CAS)
https://github.com/ndless-nspire/Ndless/issues/256

**Comment by Vogtinator** [comment] 2020-11-19 18:33
Let's close this as a duplicate of #256.

**Closed by Vogtinator** 2020-11-19 18:33 UTC
Labels: duplicate

**Comment by adriweb** [comment] 2020-11-19 18:35
(that said it's not quite a duplicate, or rather, #256 has multiple distinct issues, although maybe only one (this one) might be on Ndless' side)
