### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ElainaJeansonne** [ndless-nspire/Ndless#381] opened 2023-03-05 19:48 UTC
Is anyone working on upgrading Ndledss? I would like to help if possible, but I am not familiar with the TI programming...

**Comment by debrouxl** [comment] 2023-03-05 19:54
Duplicate of #300 ...

**Comment by Vogtinator** [comment] 2023-03-05 20:24
> I would like to help if possible, but I am not familiar with the TI programming...

Unfortunately that won't be easy, some reverse engineering of ARM assembly is required for that.

**Closed by Vogtinator** 2023-03-05 20:24 UTC

**Comment by PinkHatGithub** [comment] 2023-03-05 22:32
oh dam. alr then
