### ISSUE TITLE
WHERE IS THE NEW VERSION OF NDLESS FOR 4.5.5?!?!?!?

### ISSUE THREAD

**Issue by dom-beep** [ndless-nspire/Ndless#422] opened 2024-07-19 17:40 UTC
**We need the new update for people who bought their calculator new, or who updated to the newest version  (me) and can’t downgrade to older versions. Just release it man it’s not that hard.**

**Comment by elmerthecat** [comment] 2024-07-19 17:44
> **We need the new update for people who bought their calculator new, or who updated to the newest version (me) and can’t downgrade to older versions. Just release it man it’s not that hard.**

I would delete this. A ton of people are about to go after this post, and all of them are going to be mad. I understand your impatience, half the reason I bought my cxII was just for homebrew. Ndless is being worked on, and it will get released at some point. Sadly though, we dont know when that is. Could be released tomorrow, could be released in two years. So yeah, sorry man, most people here feel your pain.

**Comment by Vogtinator** [comment] 2024-07-19 18:59
Duplicate of #300.

**Closed by Vogtinator** 2024-07-19 18:59 UTC

**Comment by dom-beep** [comment] 2024-08-05 15:10
> > **We need the new update for people who bought their calculator new, or who updated to the newest version (me) and can’t downgrade to older versions. Just release it man it’s not that hard.**
> 
> I would delete this. A ton of people are about to go after this post, and all of them are going to be mad. I understand your impatience, half the reason I bought my cxII was just for homebrew. Ndless is being worked on, and it will get released at some point. Sadly though, we dont know when that is. Could be released tomorrow, could be released in two years. So yeah, sorry man, most people here feel your pain.

Oh it is getting worked on? I just didn’t know it stared coding.

**Comment by elmerthecat** [comment] 2024-08-06 22:03
> > > **We need the new update for people who bought their calculator new, or who updated to the newest version (me) and can’t downgrade to older versions. Just release it man it’s not that hard.**
> > 
> > 
> > I would delete this. A ton of people are about to go after this post, and all of them are going to be mad. I understand your impatience, half the reason I bought my cxII was just for homebrew. Ndless is being worked on, and it will get released at some point. Sadly though, we dont know when that is. Could be released tomorrow, could be released in two years. So yeah, sorry man, most people here feel your pain.
> 
> Oh it is getting worked on? I just didn’t know it stared coding.

The only reason that I said to delete it is that a ton of people are getting email updates whenever anyone posts anything about ndless, so they tend to get excited whenever they see an email and then get mad whenever they realize that it was not an ndless update, but was in fact just someone asking this question. I recommend following it as well if you want updates on ndless. :)
