### ISSUE TITLE
Ndless isn’t working with version 5.3.2. When will Vog release a new version?

### ISSUE THREAD

**Issue by TheRealPandaRust** [ndless-nspire/Ndless#307] opened 2021-09-03 04:16 UTC
Does anyone know when a new ndless version will be out? And if it’s possible to downgrade my current os?

**Comment by Vogtinator** [comment] 2021-09-03 18:15
Dupe of #300

There's no ETA, it's out when it's out. Downgrading isn't possible without having Ndless first.

**Closed by Vogtinator** 2021-09-03 18:15 UTC
