### ISSUE TITLE
New version of Ndless for OS 5.4?

### ISSUE THREAD

**Issue by Link1122** [ndless-nspire/Ndless#363] opened 2022-09-10 16:30 UTC
This question is for any members of the Ndless team. Are you working on a version compatible with CX Ii CAS OS 5.4? And do you have an estimate of when you'll be done? I'm trying to decide if I should return my calculator or not...

**Comment by Vogtinator** [comment] 2022-09-10 16:34
Duplicate of #300

**Closed by Vogtinator** 2022-09-10 16:34 UTC

**Comment by adriweb** [comment] 2022-09-10 16:49
If you really **can't** do without Ndless, yes I guess you can return it and try to buy a used one instead 🤷‍♂️
