### ISSUE TITLE
ndless for ti nspire 5.3.2

### ISSUE THREAD

**Issue by 4nisdz** [ndless-nspire/Ndless#340] opened 2022-03-30 23:54 UTC
Hi,
Is there any plan for 5.3.2 support? I upgraded my nspire os without doing it on purpose and now im stuck and can't downgrade.

Thanks

**Comment by debrouxl** [comment] 2022-03-31 05:37
Duplicate of #300 .

**Closed** 2022-03-31 06:43 UTC
