### ISSUE TITLE
Ndless 5.4 for Nspire cx 2 os 5.4.xxx

### ISSUE THREAD

**Issue by Sprink02** [ndless-nspire/Ndless#331] opened 2022-03-11 03:22 UTC
Is there any plans for Nspire cx 2 os 5.4.xxx
If not I have been trying to find a work around but have failed so far
If anyone has any ideas tell me

**Comment by debrouxl** [comment] 2022-03-11 08:01
Duplicate of #327 and #330 (from yesterday...).

**Closed** 2022-03-11 09:44 UTC
