### ISSUE TITLE
Update for 5.3.2.129

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Ndless#349] opened 2022-07-29 15:19 UTC
Hello. I would like to know when(if ever) there will be compatibility for version 5.3.2.129 on the calculator?

**Comment by debrouxl** [comment] 2022-07-29 15:22
Duplicate of #300 .

**Closed** 2022-07-29 15:24 UTC

**Comment by adriweb** [comment] 2022-07-29 15:25
(A new version would target the latest OS anyway, which 5.3 isn't anymore)
