### ISSUE TITLE
nspire cx cas v.4.5.5.79???

### ISSUE THREAD

**Issue by BosscarG** [ndless-nspire/Ndless#301] opened 2021-08-15 14:27 UTC
LIke an idiot i updated my tin-nspire cx CAS calculator to version 4.5.5.78 not realising ndless was availble for that version. Do you know if ndless is in development for 4.5.5.78 or is there a way i can downgrade to 4.5.4.48? when i tried to it said you can downgrade

**Comment by Vogtinator** [comment] 2021-08-15 19:15
Let's close this as a duplicate of #300.

**Closed by Vogtinator** 2021-08-15 19:15 UTC

**Comment by Djwillisdareal** [comment] 2023-09-06 01:33
> LIke an idiot i updated my tin-nspire cx CAS calculator to version 4.5.5.78 not realising ndless was availble for that version. Do you know if ndless is in development for 4.5.5.78 or is there a way i can downgrade to 4.5.4.48? when i tried to it said you can downgrade

I did the same thing I need help too

**Comment by PrazgreenStudios** [comment] 2023-09-09 07:20
so is this going to be patched?

**Comment by PinkHatGithub** [comment] 2023-09-09 14:29
this was closed, stop asking about it
