### ISSUE TITLE
[macOS] bug in the Makefile for the Ndless 4.5 installer

### ISSUE THREAD

**Issue by rawenger** [ndless-nspire/Ndless#249] opened 2020-10-17 20:23 UTC
There's a super minor bug in the makefile for the Ndless 4.5 installer (/ndless/src/installer-4.5/Makefile) at line 30 that causes the entire SDK build to fail on macOS. `base64` uses `-b` in place of `-w` as the option to set line breaks in macOS, and a quick google search revealed it's set to `0` by default. Sure enough, removing the `-w0` option from line 30 of the Makefile fixed the issue.

**Comment by Vogtinator** [comment] 2020-10-17 20:24
Dupe of https://github.com/ndless-nspire/Ndless/pull/200

**Closed by Vogtinator** 2020-10-17 20:24 UTC

**Comment by rawenger** [comment] 2020-10-17 21:01
Oh yeah you're right; for some reason that didn't show up when I searched for macOS issues
