### ISSUE TITLE
Not working in 4.5.1 (Downgrade to 4.5.0 without ndless?)

### ISSUE THREAD

**Issue by felixlee0530** [ndless-nspire/Ndless#176] opened 2019-05-12 04:22 UTC
So, as someone said a few days ago, ndless is currently not working in 4.5.1 due to some issues yet.. I accidentally updated my handheld to 4.5.1 and now this became a problem.. Of course, the computer link software prevents me to downgrade it to 4.5.0.. :(

I need to delete nLoader using the app 'Btmg' and it needs to have a ndless installation to work.

Are there any possible ways to downgrade my handheld to 4.5.0 without getting help of ndless?

Or do I just need to wait until the new ndless comes out?

Any responses would be appreciated.

P.S. I also tried reformatting (resetting) the handheld in maintenance menu, but the system would still prevent me to downgrade the OS to 4.5.0..

**Comment by trueToastedCode** [comment] 2019-05-13 14:02
Until now there is unfortunately no way to downgrade from 4.5.1 to an older version. Maybe in some time a new security breach will be found... it was the case in all updates in the past so i think it is until now no reason why not to be confident

**Comment by felixlee0530** [comment] 2019-05-13 14:10
> Until now there is unfortunately no way to downgrade from 4.5.1 to an older version. Maybe in some time a new security breach will be found... it was the case in all updates in the past so i think it is until now no reason why not to be confident

For now I am staying at 4.5.1 as I fortunately figured out a way how to bypass nLoader and boot to the new os properly. nLoader normally shows a red screen when an unsupported version of os is installed in the calculator, but a guy in tiplanet gave me a solution.

Hope the new ndless will come out soon. When do you guess?

**Comment by scrub10rd** [comment] 2019-05-14 23:10
Could you link me to that solution? I accidentally updated to 4.5.1 as well :/

**Comment by felixlee0530** [comment] 2019-05-15 00:50
> Could you link me to that solution? I accidentally updated to 4.5.1 as well :/

Do you see the red screen of death too??

**Comment by trueToastedCode** [comment] 2019-05-16 13:20
@felixlee0530 what do you mean? Don't you need Ndless to use nLoader ??

**Comment by scrub10rd** [comment] 2019-05-28 22:30
dont have nLoader, im on vanilla boot

**Comment by WoaowMusic** [comment] 2019-05-31 00:05
> > Could you link me to that solution? I accidentally updated to 4.5.1 as well :/
> 
> Do you see the red screen of death too??

I have the red screen of death on OS 4.5.1, I got a copy of 4.5.0 and I'm unable to downgrade to it because of the software.  It's allowing me to use 4.5.1 CX + CAS only.

**Comment by critor** [comment] 2019-05-31 13:44
If you followed the TI-Planet how-to, just hold [esc][Menu][Minus] for each reboot to bypass nLoader.
You should then be able to install a non-CAS version. Try non-CAS 4.5.0, and if it doesn't work then non-CAS 4.5.1.
Don't forget to hold [esc][Menu][Minus] before each reboot. If you forget, immediately press the reset button on the back.

The issue is nLoader refuses to launch unknown OS versions, and hasn't been updated with 4.5.1 support yet.

**Comment by trueToastedCode** [comment] 2019-05-31 16:07
OK, when holding [esc][Menu][Minus], the „CX CR IV DVT(2016/02/15) Diag“ comes, but how is it possble to bypass there Nloader?

**Comment by critor** [comment] 2019-05-31 16:13
Thanks for your reply. Then either you didn't accurately follow the TI-Planet nLoader how-to, either you did follow some other nLoader how-to.

Sorry, in this state, there is no way to repair the calculator through software. It can only be repaired by connecting an USB/TTL interface to the dock connector to reflash the Boot2 partition. It's usually quite cheap.

**Comment by trueToastedCode** [comment] 2019-08-14 23:01
don't think this helps to bypass
1. i found the combination doc + enter + 0 on startup ... 
-> maybe this is the missing combination on https://hackspire.org/index.php?title=Operating_System
for the touchpad boot2

2. i found out, the when interrupting the usb connection while installing old os on 4.5.1 about 0.0-0.1 before error message that the os could not be upgraded the link software on the pc says that the installation was successfull
... when looking on the storage on the calculator nothing changed... except one time but i didnt remember what i did .. but i think this is unimportant... maybe the link software just 'looks' if the calculator disconnects because this
is what normally happens when the calculatorhas installed an os successfully

**Comment by WoaowMusic** [comment] 2019-09-02 04:33
I know this is an old issue, but I was wondering if nLoader would still be present on a calculator after a new OS is installed.

**Comment by critor** [comment] 2019-09-02 06:52
Unfortunately, nLoader still hasn't been updated with OS 4.5.1 support.
Do not update to OS 4.5.1 or you're going to semi-brick your calculator.

**Comment by WoaowMusic** [comment] 2019-09-04 05:10
> 
> 
> Unfortunately, nLoader still hasn't been updated with OS 4.5.1 support.
> Do not update to OS 4.5.1 or you're going to semi-brick your calculator.

I didn't have a choice, every other OS bricked the calculator.  If nLoader was already installed from a previous CAS hack (that worked for a few months), would it still be present on the calculator?

**Comment by Vogtinator** [comment] 2019-09-14 07:36
Let's close this as dup of #173.

**Closed by Vogtinator** 2019-09-14 07:36 UTC
