### ISSUE TITLE
Ndless for Ti nspire cx ii 5.4

### ISSUE THREAD

**Issue by Chaos3800** [ndless-nspire/Ndless#373] opened 2023-01-20 10:41 UTC
Hi, will there ever be an ndless update to support 5.4 version of the nspire cx ii?

**Comment by adriweb** [comment] 2023-01-20 10:42
dup of #300 for newer version support

**Comment by debrouxl** [comment] 2023-01-20 10:42
Yet another duplicate of #300 ...

**Closed** 2023-01-20 10:44 UTC
