### ISSUE TITLE
Supporting 5.4.0.259?

### ISSUE THREAD

**Issue by m3cinc** [ndless-nspire/Ndless#336] opened 2022-03-15 19:56 UTC
My Ti-nspire CX II came with OS 5.4.0.259.
any chance an update is forthcoming soon?
I could help port on Bullseye so it could run a raspberry???

**Comment by adriweb** [comment] 2022-03-15 20:00
Nope, you can't do anything about it for now.

However it's interesting that it came with this OS. Is it brand new or did you get it used from someone else?
What's the datecode on the back to the right of the serial number? It should look like M-0621AO.

**Comment by m3cinc** [comment] 2022-03-15 22:53
Adrien,

C'est M-0521AN.
J'ai malheureusement fait l'update dès le premier contact...
Merci de suivre!
Marc

**Comment by adriweb** [comment] 2022-03-15 22:54
Dommage, il va falloir attendre une mise à jour de Ndless alors, il faut suivre #300.

**Comment by Apocryphon-X** [comment] 2022-07-18 23:35
> I updated my calculator, not knowing that leaving it at a previous version would mean that I could get more functionality from it.

Same here

**Comment by OlivierFortier** [comment] 2022-07-24 02:30
Same thing for me. Just found out about all the awesome stuff that I could do on my calculator 😕

**Comment by DerekTDR** [comment] 2022-07-24 17:00
> Supporting this update for Ndless would be awesome. I updated my calculator, not knowing that leaving it at a previous version would mean that I could get more functionality from it.
> 
> I would love to see support for this version!

Same with me

**Comment by Vogtinator** [comment] 2022-08-02 17:03
Duplicate of #300

**Closed by Vogtinator** 2022-08-02 17:03 UTC

**Comment by moralescameron** [comment] 2023-10-01 12:49
I just got my TI-Nspire CX II 
yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!

**Comment by ExpertPhisherman** [comment] 2023-10-01 12:52
> I just got my TI-Nspire CX II
> yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!

Read the thread, the topic has been extensively covered in this thread and in countless others.

**Comment by Enchanterr** [comment] 2023-10-01 12:54
> > I just got my TI-Nspire CX II
> > yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!
> 
> Read the thread, the topic has been extensively covered in this thread and in countless others.

I Did read the thread... you don't need to be so uptight about it there's no harm in asking lol

**Comment by PiplupDevelopments** [comment] 2023-10-01 12:59
> > > I just got my TI-Nspire CX II
> > > yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!
> > 
> > Read the thread, the topic has been extensively covered in this thread and in countless others.
> 
> I Did read the thread... you don't need to be so uptight about it there's no harm in asking lol

You are right... There's no harm in joining the massive amount of people who asked the exact same questions. If you actually read the thread you would know that there is no answer to that question.

**Comment by Enchanterr** [comment] 2023-10-01 13:02
> > > > I just got my TI-Nspire CX II
> > > > yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!
> > > 
> > > 
> > > Read the thread, the topic has been extensively covered in this thread and in countless others.
> > 
> > 
> > I Did read the thread... you don't need to be so uptight about it there's no harm in asking lol
> 
> You are right... There's no harm in joining the massive amount of people who asked the exact same question. If you actually read the thread you would know that there is no answer to that question.

there should be like a group formed or something so that people could form to get the developer of ndless to work on the newer updates.

**Comment by PiplupDevelopments** [comment] 2023-10-01 13:08
> > > > > I just got my TI-Nspire CX II
> > > > > yesterday and realized its also on 5.4.259 Any update on support coming?? I really wanted this!!
> > > > 
> > > > 
> > > > Read the thread, the topic has been extensively covered in this thread and in countless others.
> > > 
> > > 
> > > I Did read the thread... you don't need to be so uptight about it there's no harm in asking lol
> > 
> > You are right... There's no harm in joining the massive amount of people who asked the exact same question. If you actually read the thread you would know that there is no answer to that question.
> 
> there should be like a group formed or something so that people could form to get the developer of ndless to work on the newer updates. 

If you read the thread you would know there is.
