### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by Respite09** [ndless-nspire/Ndless#409] opened 2024-02-09 15:29 UTC
How is progress on the new version?

**Comment by debrouxl** [comment] 2024-02-09 15:41
Duplicate of #300 ...

**Comment by Respite09** [comment] 2024-02-09 16:55
it's just been a long time... I don't know if it's still being worked on or not.

**Comment by ExpertPhisherman** [comment] 2024-02-09 17:02
> it's just been a long time... I don't know if it's still being worked on or not.

Stop asking

**Closed** 2024-02-10 21:48 UTC
