### ISSUE TITLE
make: *** [Makefile:852: all] Error 2

### ISSUE THREAD

**Issue by Kunait** [ndless-nspire/Ndless#216] opened 2020-06-13 22:18 UTC
I'm using the Windows Subsystem for Linux and I followed the instructions, but I always get this error when I try to execute 'build_toolchain.sh'. I even read some other issues where it was said to change the PATH before using the command 'make', and even though I didn't use it I still changed it before I built the toolchain (as my second attempt, the first time I didn't change it yet), but nothing changed. I even the complete clone from Github and tried again several times, but it won't work :(
I really hope I didn't miss an issue where this problem was already discussed, but I couldn't find one.

![Error 2](https://user-images.githubusercontent.com/16063133/84580101-2560e300-add4-11ea-9d1a-13fa3745a5ab.png)

**Comment by Vogtinator** [comment] 2020-06-13 22:20
The actual error message is further backwards in the output, can you look for it? It most likely contains `Error:`.

**Comment by Kunait** [comment] 2020-06-13 22:32
I couldn't find anything in that format, but I'm currently re-running the command and saving the output to a file, gonna upload it in a min

**Comment by Kunait** [comment] 2020-06-13 22:35
Here it is, in my terminal it looked much longer but well :/

[output.txt](https://github.com/ndless-nspire/Ndless/files/4775612/output.txt)

**Comment by Vogtinator** [comment] 2020-06-13 22:39
> sleep: cannot read realtime clock: Invalid argument

Looks like WSL is broken, it does not support reading the clock. This apparently leads to `make` wanting to build the prebuild manual for `binutils`, which needs the `makeinfo` package.

As a workaround, you could simply install `makeinfo`. Or switch to something which isn't as broken as WSL...

**Comment by adriweb** [comment] 2020-06-13 22:40
Speaking of which, WSL2 might be worth a try?

**Comment by Kunait** [comment] 2020-06-13 22:42
Gonna try installing makeinfo, hope that works :/

**Comment by Kunait** [comment] 2020-06-13 23:57
@Vogtinator Thank you so much for helping me even though it's this late(at least here in Germany). I would love to contribute to the project but I don't think I am skilled enough for that :(

**Comment by Kunait** [comment] 2020-06-14 00:02
Ok maybe I shouldn't have been this optimistic because I have a different error know, when I use 'make' it says that it can't find 'arm-none-eabi-g++' even though I set the path(at least I hope I did it right :/)

**Comment by Kunait** [comment] 2020-06-14 00:21
I don't think it will help, but I'm currently updating to WSL2 as @adriweb suggested, lets hope it works

**Comment by adriweb** [comment] 2020-06-14 01:32
Well, when you do `which arm-none-eabi-g++` does it find it? If yes, something else is wrong, if not, PATH isn't set correctly. Either way, when you launch it manually via its full path, does it launch? (and just gives an error about no input file)

**Comment by Kunait** [comment] 2020-06-14 01:54
@adriweb Very good question, sadly I didn't test that, I had no hope so I deinstalled WSL and reinstalled it so nothing of my previous attempts is left. I will try again tomorrow and post here again if it doesn't work again. I really hope it does work because else I will have to use cygwin again but the last time I tried that I again only had problems :(

**Comment by Kunait** [comment] 2020-06-14 02:16
Didn't want to close it...

**Comment by Kunait** [comment] 2020-06-14 14:31
Sadly I'm back again, now I got a different error, the terminal returns './build_toolchain.sh: 72: make: not found'

**Comment by Vogtinator** [comment] 2020-06-14 14:32
Just install `make` then.

**Comment by Kunait** [comment] 2020-06-14 14:42
Ok, I installed make (idk why it wasn't installed before :( ), now the installation continues but I get neither a 'Done!' at the end nor any error it just says:

configure: updating cache ./config.cache
configure: updating cache ./config.cache
configure: creating ./config.status
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating testsuite/Makefile
config.status: creating config.h
config.status: creating config.h
config.status: executing default commands
config.status: executing default commands

and then it stops.


(Btw thank you so much for helping, I bet you have a lot of stuff to do)

**Comment by Vogtinator** [comment] 2020-06-14 14:46
Please upload the whole output somewhere,  maybe try `sh -x build_toolchain.sh` for more verbose output.

**Comment by Kunait** [comment] 2020-06-14 14:51
Here it is


[output.txt](https://github.com/ndless-nspire/Ndless/files/4776634/output.txt)

**Comment by Vogtinator** [comment] 2020-06-14 14:52
> configure: error: C++ compiler missing or inoperational

Please make sure you installed all the required dependencies first.

**Comment by Kunait** [comment] 2020-06-14 15:08
I tried to follow the tutorial on Hackspire line by line I don't know why anything is missing...

**Comment by Vogtinator** [comment] 2020-06-14 15:13
At least `make` is not mentioned indeed, but `g++` is. There is no complete list of packages though, so if you want to help you could add one. An incomplete one for Debian-based systems is on https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction already.

FYI, I just merged #211, so I recommend that you `git pull` before building the toolchain, otherwise it'll be outdated again already.

**Comment by Kunait** [comment] 2020-06-14 15:20
Well the build process is currently running, should I stop it or rather wait until its finished and then pull?

And I could try to add some packages I installed for WSL if it works in the end, so at least there is a way I can help

**Comment by Vogtinator** [comment] 2020-06-14 15:23
> Well the build process is currently running, should I stop it or rather wait until its finished and then pull?

It would have to start from scratch anyway, so if it's not almost done already it makes sense to abort this and restart.

> And I could try to add some packages I installed for WSL if it works in the end, so at least there is a way I can help

Yep, that would be very useful for others.

**Comment by Kunait** [comment] 2020-06-14 15:43
I have a question, in the new build-toolchain.sh you started the script with #!/bin/sh, but the script doesn't work (at least for me). I had to change it to #!/bin/bash because else it couldn't find pushd and  immediately gave me an error

**Comment by Vogtinator** [comment] 2020-06-14 15:51
TIL, fixed now.

**Comment by Kunait** [comment] 2020-06-14 17:37
Is it normal that it is taking over 2 hours now? I am starting to doubt that it will ever finish :D

**Comment by adriweb** [comment] 2020-06-14 17:39
Yes, it can take several hours especially when running "non-natively". You hopefully only have to do that once, or at least rarely.

**Comment by Kunait** [comment] 2020-06-14 17:40
Ok that gives me hope, I reaaaally hope that it will work this time else I might go insane xD

**Comment by Kunait** [comment] 2020-06-14 17:59
Ok, it finished but I got the same error as in the beginning, it can't find the arm-none-eabi-g++, I will try it with the whole path

**Comment by adriweb** [comment] 2020-06-14 18:00
What did the log say at the end?

**Comment by Kunait** [comment] 2020-06-14 18:01
[makeoutput.txt](https://github.com/ndless-nspire/Ndless/files/4776978/makeoutput.txt)

**Comment by adriweb** [comment] 2020-06-14 18:04
That's the end of the log after you launched `build_toolchain.sh` under WSL2 ?
Anyway, yeah, try to see what's happening when you launch `arm-none-eabi-g++` manually. What's its path? Also, what does `echo $PATH` give ?

**Comment by Kunait** [comment] 2020-06-14 18:05
1. Yes
2. I couldn't find it currently still searching
3./usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Python38/Scripts/:/mnt/c/Python38/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files (x86)/Calibre2/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/Kunait/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Kunait/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Kunait/AppData/Roaming/npm:/mnt/c/Users/Kunait/flutter/bin:/snap/bin

It doesn't seem to be in the PATH even though I added it, I really don't know why...

**Comment by adriweb** [comment] 2020-06-14 18:08
Right, well, at the very beginning of the path, add (prepend) the path to the bin folder where `arm-none-eabi-g++` is.

**Comment by Kunait** [comment] 2020-06-14 18:33
I can't find any info on which file I should use, I already modified my ~/.profile file to add to PATH but that didn't work, which file should I use?

**Comment by adriweb** [comment] 2020-06-14 18:36
it's the `.bashrc` file in the home directory of the wsl user. So, for instance, with nano: `nano ~/.bashrc`

**Comment by Kunait** [comment] 2020-06-14 18:48
Oh man I don't know what I did but I must have modified a file wrongly because WSL won't start anymore and when it does Bash doesn't work... Gonna try to fix it

**Comment by Kunait** [comment] 2020-06-14 18:58
Ok I officially destroyed my WSL, because I use WSL2 now I can't modify any files because Windows now saves them in a .vhdx format and I can't mount that because it says the drive is already mounted, I must have fucked up something in the path variable because nothing works anymore, WSL won't even boot it just says something like couldn't connect to host

**Comment by adriweb** [comment] 2020-06-14 19:00
Well, I'm not sure what you did, but it doesn't sound like a simple mistake in .bashrc is supposed to cause that bad of an issue.
Try rebooting your computer?

**Comment by Kunait** [comment] 2020-06-14 19:05
I did but still the same issue, damn this is so fucking dumb for several hours I tried and tried but now Windows just fucks me up, if I wasn't gaming a lot I would deinstall Windows faster than McAfee

**Comment by adriweb** [comment] 2020-06-14 19:07
You can always fully uninstall WSL, install a Linux VM instead, and that will work without any issues.

**Comment by Kunait** [comment] 2020-06-14 19:08
Yeah I think I'll have to do that, but the WSL was so convenient yk, no waiting for Bootup, easy access to files in Windows and vice versa, but well you have to do what you have to do

**Comment by adriweb** [comment] 2020-06-14 19:09
I'm fairly sure that it's still possible to make everything work in WSL, you may just have had bad luck several times.

**Comment by Kunait** [comment] 2020-06-14 19:16
I think so, too. But I really don't want to mess with it anymore, I already reinstalled it 2 times and I'm trying to install everything since yesterday but it didn't want to work. Sometimes we have to accept signs xD

**Comment by Kunait** [comment] 2020-06-14 23:31
Guys I am slowly losing my mind because of this, I was able to build the toolchain, but I can't change my PATH variable, no matter what I try it will not work. When I use the template given on. the hackspire site or what @Vogtinator sent in this Issue it says invalid identifier '=' and it doesn't add anything to the path and when I try some other things it just destroys my bash and no command works because it somehow destroys the path variable and I have to undo everything and restart so it gets reset. I really have no idea what to do now, I tried it in ~/.profile , .bashrc and even with . bashprofile but nothing works the PATH just won't change or when something happens it just corrupts my PATH and nothing works anymore... You have any idea what I can do? At this point I have no idea anymore

**Comment by adriweb** [comment] 2020-06-15 00:19
Copy the contents of your .bashrc file here, you're probably just not writing the export command correctly...

**Comment by Vogtinator** [comment] 2020-06-15 06:09
You don't even have to change `PATH` persistently, just run the export in the current session to be able to build the SDK.

**Comment by Kunait** [comment] 2020-06-15 13:40
At the end of .bashrc I just added export PATH = "home/CDev/Ndless/ndless-sdk/toolchain/install/bin:home/CDev/Ndless/ndless-sdk/bin:${PATH}

Just like the tutorial showed.

**Comment by Vogtinator** [comment] 2020-06-15 13:42
I see two issues with that line. You forgot the `/` before `home/` and also added spaces around the ` = `. Both have to be fixed to make it work as expected.

**Comment by Kunait** [comment] 2020-06-15 13:43
Ok, I'll try

**Comment by Kunait** [comment] 2020-06-15 13:46
Ok, it finally added to the PATH, thanks for that, but I still get an error. Here is the output:
[outputmake.txt](https://github.com/ndless-nspire/Ndless/files/4780599/outputmake.txt)

**Comment by Vogtinator** [comment] 2020-06-15 13:50
That means it didn't use the right toolchain for building. Please make sure that `PATH` is indeed set correctly and `which arm-none-eabi-gcc` returns the correct path.

**Comment by Kunait** [comment] 2020-06-15 13:53
`which arm-none-eabi-gcc` returns _/home/kunait/CDev/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-gcc_ so the path is set I think

**Comment by Vogtinator** [comment] 2020-06-15 14:00
Ok, that looks good. Please `cd` into `ndless-sdk/libsyscalls` and post the output of `arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -o realpath.o -v`.

**Comment by Kunait** [comment] 2020-06-15 14:02
Here it is
[armnoneoutput.txt](https://github.com/ndless-nspire/Ndless/files/4780705/armnoneoutput.txt)

**Comment by Vogtinator** [comment] 2020-06-15 14:12
That's also looking good, so this is indeed an issue I've not seen before.

Does `ndless-sdk/toolchain/install/arm-none-eabi/sys-include/sys/syslimits.h` exist and contain `#define PATH_MAX`?

If yes, please provide the output of `arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -dD -E`. Warning: It will be long (~4k lines)

**Comment by Kunait** [comment] 2020-06-15 14:16
The sys folder doesn't exist, so syslimits.h also doesn't exist

**Comment by Vogtinator** [comment] 2020-06-15 15:30
Yay, I can reproduce the issue after removing all remnants of my toolchain here and doing a clean rebuild with the new script and updated versions. I'll investigate why it broke.

**Comment by Kunait** [comment] 2020-06-15 15:36
So I did everything right this time? Damn xD

**Comment by Vogtinator** [comment] 2020-06-15 18:04
It was indeed caused by #211, a path wasn't updated correctly so it only worked by accident as I still had the right headers in the target location...

I'm currently running a clean build to verify that it's indeed a complete and working fix before I merge it though. If it's not working, I'll revert #211 temporarily until this is fixed properly.

**Comment by Vogtinator** [comment] 2020-06-15 19:39
Yep, it works.

So please `git pull; rm .built_gcc_step2; ./build_toolchain.sh` and try again.

It's possible that just rebuilding stage 2 is not enough, in that case `rm .built_gcc* .built_newlib; ./build_toolchain.sh`.

**Closed** 2020-06-15 19:38 UTC

**Comment by Kunait** [comment] 2020-06-16 00:51
I just deleted everything and tried again because it was fast enough in my VM, but I got the same error again.

**Comment by Kunait** [comment] 2020-06-16 00:58
But I found nspire-gcc and it alone seems to work, when I run it without a file it returns the expected output.

**Comment by Vogtinator** [comment] 2020-06-16 09:25
Ok, so something is still wrong with the new `build_toolchain.sh` script. I reverted #211 now.

So you'll have to `git pull; rm -r install .built_* .downloaded; ./build_toolchain.sh` again, unfortunately...

Thanks for your patience!

**Comment by Kunait** [comment] 2020-06-16 09:31
Ok, gonna try that now. Thank you, too. Without your help I wouldn't have even gotten this far

**Comment by Kunait** [comment] 2020-06-16 12:39
So just as a finishing comment, it worked now, I even compiled something. Thank you @adriweb @Vogtinator

**Comment by Vogtinator** [comment] 2020-06-16 12:43
Yay!

**Comment by Vogtinator** [comment] 2020-06-18 19:50
The fix in #218 was in the right direction, but not complete - gcc step 1 also needs those includes, but at that point newlib wasn't downloaded and extracted yet.

If you have time, you could try the hopefully finally fully fixed new toolchain script and enjoy GCC 10:

`git pull origin; git checkout toolchainscript; rm .built* ./build_toolchain.sh`

(You'll have to switch back with `git checkout master` once it's merged)
