### ISSUE TITLE
Ti-Nspire CX II 5.4

### ISSUE THREAD

**Issue by Royalebruve** [ndless-nspire/Ndless#330] opened 2022-03-10 00:49 UTC
ti nxpire accomplishes this once more I finally got myself a new tispire 2 calc only to find it in 5.4 version my older calc is no longer in any condition to be used I tried reverting the new calc version but it says an error message "ms you cannot install a version of the os that is older than the currently installed version " please tell me if I can revert my tinxpire to an older version in order to download ndless

**Comment by mcgregol** [comment] 2022-03-10 03:32
Duplicate of #327

**Closed** 2022-03-10 07:48 UTC
