### ISSUE TITLE
TI-nspire CX II Version: 5.4.0.259

### ISSUE THREAD

**Issue by percyjackson2213** [ndless-nspire/Ndless#396] opened 2023-10-08 20:35 UTC
Hi, Is there any version that is compatible with TI-nspire CX II Version: 5.4.0.259 because the latest release didnt work for me, I got an error.

**Comment by ExpertPhisherman** [comment] 2023-10-08 20:37
no, read the other threads before asking the same question that has been answered hundreds of times

**Comment by percyjackson2213** [comment] 2023-10-08 20:41
Sorry, but there is nothing else relating to 5.4?

**Comment by ExpertPhisherman** [comment] 2023-10-08 20:42
dupe of #300

**Comment by percyjackson2213** [comment] 2023-10-08 20:43
??? That is 5.3 what similarity are you seeing? there is a download for 5.2-5.3 not one for 5.4

**Comment by adriweb** [comment] 2023-10-08 20:43
it's the same, #300 is applicable to any new version not currently supported by the version listed on ndless.me or the readme here.

Regardless, 5.4 is also not a target if 6.0 can be targeted.

**Comment by percyjackson2213** [comment] 2023-10-08 20:46
Yes, I see but is it the same result where I just have to wait for the correct ndless version is released. and also looks like that wont come out for ages.

**Comment by adriweb** [comment] 2023-10-08 20:47
Yes...

**Closed** 2023-10-08 20:48 UTC
