### ISSUE TITLE
Ndless in a Ti-ninspire CX ii-T with version 5.4.0.259 don't work

### ISSUE THREAD

**Issue by YassiGame** [ndless-nspire/Ndless#369] opened 2022-11-13 15:28 UTC
Hello I have a Ti-nspire CX **ii**-T with version **5.4.0.259**, when I want to install Ndless it doesn't work I followed the tutorial and everything but it doesn't work I always get this error...

![image](https://user-images.githubusercontent.com/78267880/201529715-65383a6b-94d4-4676-b53d-d1d222240996.png)

And my files:
![image](https://user-images.githubusercontent.com/78267880/201529748-cad59422-6ced-477c-9e24-8fd003f6e18b.png)

**Comment by debrouxl** [comment] 2022-11-13 15:29
Another duplicate of #300 .

**Comment by YassiGame** [comment] 2022-11-13 15:32
ah okay my bad

**Closed** 2022-11-14 07:28 UTC
